# This is a basic workflow to help you get started with Actions

name: Test CI/CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test ]
  pull_request:
    types: [closed]
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # test our application       
  testBeforeDeploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # test only if branche is test and pull request is approved or merged
    if: github.event.pull_request.merged == true
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checks-out Repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      # install applicaion dependencies
      - name: Install Dependencies & angular
        run: |
          npm install
          npm install -g @angular/cli 

      # run a set of test commands
      - name: Testing
        run: echo 'Test Completed!'
        